#!/bin/bash

link() {
  src="${HOME}/.dotfiles/${1}"
  # If file/dir doesn't exist, exit
  if [[ -e "${src}" ]]; then
    ln -sfn "${src}" "${HOME}/${2}"
    echo "Linked ~/${2}"
  else
    echo "File doesn't exist: ${src}"
  fi
}

echo "Symlinking files..."

link "git/gitconfig" ".gitconfig"
link "git/gitignore" ".gitignore"

echo "Symlinking complete!"
