#!/bin/bash

link() {
  src="${HOME}/.dotfiles/${1}"
  # If file/dir doesn't exist, exit
  if [[ -e "${src}" ]]; then
    ln -sfn "${src}" "${HOME}/${2}"
    echo "Linked ~/${2}"
  else
    echo "File doesn't exist: ${src}"
  fi
}

echo "Symlinking files..."

link "git/gitconfig" ".gitconfig"
link "git/gitignore" ".gitignore"
link "zsh/zshrc" ".zshrc"
link "zsh/zsh_profile" ".zsh_profile"
link "i3/config" ".config/i3/config"
link "i3/i3blocks.conf" ".config/i3/i3blocks.conf"

echo "Symlinking complete!"
