# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch notify
bindkey -e

export ZSH=/home/simon/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git command-not-found git-extras pip npm)

source $ZSH/oh-my-zsh.sh

# include Z
. ~/z.sh

prompt_context() {}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# React Native env variables for Android
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

#go
export GOROOT=/usr/local/go
export GOPATH=$HOME/dev/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

export PATH=~/.local/bin:$PATH
